module.exports = (sequelize, type) => {
  return sequelize.define('zipcode',
                          {zip: {type: type.STRING,
                                 primaryKey: true},
                           lat: type.STRING,
                           lng: type.STRING,
                           city: type.STRING,
                           state_id: type.STRING,
                           state_name: type.STRING,
                           zcta: type.STRING,
                           parent_zcta: type.STRING,
                           population: type.STRING,
                           density: type.STRING,
                           county_fips: type.STRING,
                           county_name: type.STRING,
                           county_weights: type.STRING,
                           county_names_all: type.STRING,
                           county_fips_all: type.STRING,
                           imprecise: type.STRING,
                           military: type.STRING,
                           timezone: type.STRING },
                          {freezeTableName: true,
                           timestamps: false});
};
